server:
  port: 8080
  servlet:
    content-type: text/html
    context-path:
    multipart:
        max-file-size: 300MB
        max-request-size: 300MB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssmbook?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    cache: false
#    mode: HTML5
#    prefix: classpath:/templates/
#    suffix: .html
#    encoding: UTF-8
    mvc:
      static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.example.springbootdemo.entity
configuration:
  map-underscore-to-camel-case: true
logging:
  config: classpath:logback.xml
  level:
    com:
      springboot: debug
fileLocation: static/files