package com.project.Dao;

import com.project.entity.Bookstock;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface BookstockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookstock
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookstock
     *
     * @mbggenerated
     */
    int insert(Bookstock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookstock
     *
     * @mbggenerated
     */
    Bookstock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookstock
     *
     * @mbggenerated
     */
    List<Bookstock> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookstock
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Bookstock record);
}