package com.project.Dao;

import com.project.entity.Viptable;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface ViptableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viptable
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer vipid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viptable
     *
     * @mbggenerated
     */
    int insert(Viptable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viptable
     *
     * @mbggenerated
     */
    Viptable selectByPrimaryKey(Integer vipid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viptable
     *
     * @mbggenerated
     */
    List<Viptable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viptable
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Viptable record);
}