package com.example.springbootdemo.entity;

import java.io.Serializable;

public class Bookstock implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookstock.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookstock.stock
     *
     * @mbggenerated
     */
    private String stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookstock.StockAddress
     *
     * @mbggenerated
     */
    private String stockaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bookstock
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookstock.ID
     *
     * @return the value of bookstock.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookstock.ID
     *
     * @param id the value for bookstock.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookstock.stock
     *
     * @return the value of bookstock.stock
     *
     * @mbggenerated
     */
    public String getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookstock.stock
     *
     * @param stock the value for bookstock.stock
     *
     * @mbggenerated
     */
    public void setStock(String stock) {
        this.stock = stock == null ? null : stock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookstock.StockAddress
     *
     * @return the value of bookstock.StockAddress
     *
     * @mbggenerated
     */
    public String getStockaddress() {
        return stockaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookstock.StockAddress
     *
     * @param stockaddress the value for bookstock.StockAddress
     *
     * @mbggenerated
     */
    public void setStockaddress(String stockaddress) {
        this.stockaddress = stockaddress == null ? null : stockaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookstock
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", stock=").append(stock);
        sb.append(", stockaddress=").append(stockaddress);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}