package com.example.springbootdemo.entity;

import java.io.Serializable;

public class Viptable implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column viptable.VIPID
     *
     * @mbggenerated
     */
    private Integer vipid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column viptable.Grade
     *
     * @mbggenerated
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column viptable.Consumption
     *
     * @mbggenerated
     */
    private Double consumption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table viptable
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column viptable.VIPID
     *
     * @return the value of viptable.VIPID
     *
     * @mbggenerated
     */
    public Integer getVipid() {
        return vipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column viptable.VIPID
     *
     * @param vipid the value for viptable.VIPID
     *
     * @mbggenerated
     */
    public void setVipid(Integer vipid) {
        this.vipid = vipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column viptable.Grade
     *
     * @return the value of viptable.Grade
     *
     * @mbggenerated
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column viptable.Grade
     *
     * @param grade the value for viptable.Grade
     *
     * @mbggenerated
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column viptable.Consumption
     *
     * @return the value of viptable.Consumption
     *
     * @mbggenerated
     */
    public Double getConsumption() {
        return consumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column viptable.Consumption
     *
     * @param consumption the value for viptable.Consumption
     *
     * @mbggenerated
     */
    public void setConsumption(Double consumption) {
        this.consumption = consumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viptable
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vipid=").append(vipid);
        sb.append(", grade=").append(grade);
        sb.append(", consumption=").append(consumption);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}