package com.example.springbootdemo.Dao;

import com.example.springbootdemo.entity.Viptable;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
public interface ViptableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viptable
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer vipid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viptable
     *
     * @mbggenerated
     */
    int insert(Viptable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viptable
     *
     * @mbggenerated
     */
    Viptable selectByPrimaryKey(Integer vipid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viptable
     *
     * @mbggenerated
     */
    List<Viptable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viptable
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Viptable record);
}